/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PromoCodeService } from "../promoCode.service";
import { PromoCodeCreateInput } from "./PromoCodeCreateInput";
import { PromoCode } from "./PromoCode";
import { PromoCodeFindManyArgs } from "./PromoCodeFindManyArgs";
import { PromoCodeWhereUniqueInput } from "./PromoCodeWhereUniqueInput";
import { PromoCodeUpdateInput } from "./PromoCodeUpdateInput";

export class PromoCodeControllerBase {
  constructor(protected readonly service: PromoCodeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PromoCode })
  async createPromoCode(
    @common.Body() data: PromoCodeCreateInput
  ): Promise<PromoCode> {
    return await this.service.createPromoCode({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PromoCode] })
  @ApiNestedQuery(PromoCodeFindManyArgs)
  async promoCodes(@common.Req() request: Request): Promise<PromoCode[]> {
    const args = plainToClass(PromoCodeFindManyArgs, request.query);
    return this.service.promoCodes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PromoCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async promoCode(
    @common.Param() params: PromoCodeWhereUniqueInput
  ): Promise<PromoCode | null> {
    const result = await this.service.promoCode({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PromoCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePromoCode(
    @common.Param() params: PromoCodeWhereUniqueInput,
    @common.Body() data: PromoCodeUpdateInput
  ): Promise<PromoCode | null> {
    try {
      return await this.service.updatePromoCode({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PromoCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePromoCode(
    @common.Param() params: PromoCodeWhereUniqueInput
  ): Promise<PromoCode | null> {
    try {
      return await this.service.deletePromoCode({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
